### ISSUE TITLE
secret

### ISSUE THREAD

**Issue by joachimprinzbach** [justincoon/coins#1]
Hey bro

you should not check your secret file in - remove it from github ;)

**Comment by hydrius** [comment]
He is extremely lucky his api key doesn't have permissions for transactions.

**Comment by justincoon** [comment]
wow thanks for the catch guys. lesson learned, just because you scope your API keys well doesn't mean you can be a dipshit with them

**Comment by justincoon** [comment]
deleted and key revoked
